INSERT INTO role (role_name) VALUES ('administrator'), ('general user');


INSERT INTO "user" (username, email, password, role_id, date_added, bio) VALUES ('Zeus', 'god_of_lightning@fake-email.com', 'scrypt:32768:8:1$P3fn40PccjmNfnqn$61efb1616bceebef1f1a6ab2fa17adb0371b137ff6032ba37d78f43989cdffa97a2e905d5330650cdee00061d6583d48205289825d4ddd2687038992ce6f5612',1, now(), '⚡ King of the Gods | Ruler of Mount Olympus | Master of Thunder & Lightning ⚡ | Sky Enthusiast | From storms to calm skies, I control it all |  Power moves only | #OlympusStrong #GodGoals');
INSERT INTO "user" (username, email, password, role_id, date_added, bio) VALUES ('Poseidon', 'god_of_sea@fake-email.com', 'scrypt:32768:8:1$WWK0k67bpQobFvGl$60915e86b97e5224d61597875ef2a0b0330dfd3b9073f52c05eaf5b2df6830d26516a93bc0cff5a7bcda143a005dd52644072b0b3aff1673c2c287999e085670', 2, now(), '🌊 God of the Seas, Lord of Oceans and Rivers | Earthshaker when I am in a mood | Master of Storms, Waves, and Horses 🐎 | Ruler of Atlantis, Protector of Sailors | When the tide turns, it’s always in my favor | #TideMaster #OceanKing');

INSERT INTO following (follower_id, followed_id) VALUES (1,2), (2,1);

INSERT INTO post (title, content, author_id, date_added) VALUES ('How do you deal with sibling rivalry?', 'Let’s just say my brothers (Poseidon and Hades) don’t always see eye to eye with me on how to run things. What’s the best way to maintain harmony without showing favoritism or sparking conflict?', 1, now()), ('How do you stay motivated when your work is overlooked?', 'I rule the seas and shake the earth, but sometimes it feels like all the attention goes to the skies (looking at you, Zeus). How do you keep pushing forward when you feel underappreciated?', 2, now());
INSERT INTO comment (content, author_id, post_id, date_added) VALUES ('Ah, the King of the Gods struggling with balance? You don’t say! Maybe if you weren’t throwing lightning bolts every time you get a little stressed, you’d have more time for family dinners. 😉 But hey, ruling Olympus sounds exhausting. Down in the seas, I deal with a lot too, but at least the tide knows how to follow my lead without constant reminders. My advice? Try a gentler approach—less thunder, more patience. It works wonders underwater. 🌊 #JustSaying', 2, 1, now()), ('Overlooked? Brother, you rule the entire ocean! The seas are literally 70% of the world! I’ve seen you create storms that would make anyone notice. Maybe the issue isn’t others not seeing you, but you not recognizing your own influence. Just because the skies are clearer doesn’t mean your waves aren’t being felt. Maybe you should spend less time worrying about Olympus and more time appreciating your kingdom below. ⚡️ #ThunderousTruth', 1, 2, now());
